### ISSUE TITLE
Error on KeycloakResourceOwner 

### ISSUE THREAD

**Issue by leakhand** [avdevs/keycloak#1]
Every line you have use Elvis operator.

return $this->response['name'] ?: null; // get E_NOTICE, if $response['name'] eq false

     /**
     * Get resource owner id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->response['sub'] ?: null;
    }

    /**
     * Get resource owner email
     *
     * @return string|null
     */
    public function getEmail()
    {
        return $this->response['email'] ?: null;
    }

    /**
     * Get resource owner name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->response['name'] ?: null;
    }

I can create pull request for you to update

**Comment by avdevs** [comment]
Yes Please
Thanks

**Comment by leakhand** [comment]
I've sent PR .
