### ISSUE TITLE
Can provide more detail step for installation?

### ISSUE THREAD

**Issue by kstan79** [avdevs/keycloak#5]
Hi, I'm feel interested in this project however however Im confuse with your installation step. It stated we shall perform `git clone https://github.com/avdevs/keycloak.git`, but it didnt state where it shall clone too, and which package in socialiteproviders shall we use. 

Can you provide more detail guidance?

**Comment by leakhand** [comment]
the installation should use this command
composer require avdevs/keycloak

**Comment by avdevs** [comment]
Hi kstan79
You can use this as Laravel Socialite Package using "composer require avdevs/keycloak"
